sudo: required

services:
  - docker

script:
  - export CONTAINER_USER=$(id -u)
  - XDEBUG=1 docker-compose build
  - docker-compose run --rm app composer install
  - docker-compose up -d
  - curl -f 127.0.0.1:1345